on:
  push:
jobs:
  dispatch:
    uses: ./.github/workflows/target-action.yml
    with:
      VARS: ${{ toJson(vars) }}
    secrets:
      DOCKERHUB_USERNAME: DOCKERHUB_USERNAME
      DOCKERHUB_PASSWORD: DOCKERHUB_PASSWORD
      DIGITALOCEAN_SSH_PRIVATE_KEY: DIGITALOCEAN_SSH_PRIVATE_KEY
