name: Generate .env and pass it to another job

on:
  workflow_dispatch:
    inputs:
      input_environment:
        description: >
          Environment from which secrets will be read.
        type: environment
        required: false
jobs:
  use_environment_and_call_display_final_dotenv:
    uses: './.github/workflows/display_final_dotenv.yml'
    with:
      ENVIRONMENT: ${{ inputs.input_environment }}
      DOTENV_CONTENT: ${{ toJson(vars) }}
      IS_JSON_STRING: true