name: Generate .env and pass it to another job

on:
  workflow_dispatch:
    inputs:
      input_choice:
        description: >
          Choice input
        type: choice
        options:
          - foo
          - bar
          - baz
      input_environment:
        description: >
          Environment from which secrets may be read
        type: environment
        required: false

jobs:
  call_display_final_dotenv:
    uses: './.github/workflows/display_final_dotenv.yml'
    with:
      ENVIRONMENT: ${{ inputs.input_environment }}
