name: Generate ouput in job

on:
  push:
  workflow_dispatch:

jobs:
  compute_dotenv_content:
    environment: lab
    runs-on: ubuntu-latest
    # outputs:
    #   dotenv_content: ${{ steps.step1.outputs.FOO }}
    steps:
     - name: Prepare .env to pass via input.DOTENV_CONTENT
       env:
        SECRET_CONTENT: ${{ toJson(secrets) }}
        VARS_CONTENT: ${{ toJson(vars) }}
       run: |
        echo $VARS_CONTENT > vars_content.json 
        echo $SECRET_CONTENT > secrets_content.json 
        cat vars_content.json | jq -r 'to_entries | map(select(.key | test("[A-Z_]+"))) | .[] | "\(.key)=\(@json \(.value))"' > output.txt
        cat secrets_content.json | jq -r 'to_entries | map(select(.key | test("[A-Z_]+"))) | .[] | "\(.key)=\(@json \(.value))"' >> output.txt
        cat output.txt
