name: Generate ouput in job

on:
  push:
  workflow_dispatch:

jobs:
  compute_dotenv_content:
    environment: lab
    runs-on: ubuntu-latest
    # outputs:
    #   dotenv_content: ${{ steps.step1.outputs.FOO }}
    steps:
     - name: Prepare .env to pass via input.DOTENV_CONTENT
       run: >
        echo '${{ toJSON(vars) }}' | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' > "$GITHUB_OUTPUT"
      