name: 'Project redeployment'

on:
  pull_request:
  # push:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: The environment of the workflow.
        required: true
      
  workflow_call:
    inputs:
      VARS:
        type: string
        required: false
    secrets:
      SECRETS:
        required: false

jobs:
  just_do_it:
    runs-on: ubuntu-latest
    environment: lab
    env:
      secretsSECRETS: ${{ secrets.SECRETS }}
      inputsVARS: ${{ inputs.VARS }}
    steps:     
      - run: |
          echo "${{ env.env_toJson_vars }}"
          echo "${{ env.secretsSECRETS }}"
          echo "${{ env.inputsVARS }}"
        env:
          env_toJson_vars: ${{ toJson(vars) }}